services:
  - type: web
    name: tool-management-system
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    port: 80
    envVars:
      - key: APP_KEY
        generateValue: true
