services:
  - type: web
    name: tool-management-system
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install
      npm run build
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_NAME
        value: "Tool Management System"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: DB_CONNECTION
        fromDatabase:
          name: tool-management-db
          property: connectionString
    databases:
      - name: tool-management-db
        databaseName: toolmanagement
        user: toolmanagement

